Repository abodnar1/zen-in-ten, pull requests merged in 2022-07, with the labels that each got.

#7 Feature/component architecture
  package-lock.json
  package.json
  public/assets/landingPage.jpg
  public/index.html
  src/App.test.tsx
  src/App.tsx
  src/App/App.css
  src/App/App.tsx
  src/Favorites/Favorites.css
  src/Favorites/Favorites.tsx
  src/Form/Form.css
  src/Form/Form.tsx
  src/QuoteCard/QuoteCard.css
  src/QuoteCard/QuoteCard.tsx
  src/Quotes/Quotes.css
  src/Quotes/Quotes.tsx
  src/Welcome/Welcome.css
  src/Welcome/Welcome.tsx
  src/index.tsx
  src/logo.svg
  src/reportWebVitals.ts
Labels: enhancement

#9 Feature/build formselect
  src/App/App.tsx
  src/Form/Form.tsx
  src/QuoteCard/QuoteCard.tsx
  src/Quotes/Quotes.tsx
Labels: enhancement

#13 Add interface file; import QuoteInterface to all necessary components
  src/App/App.tsx
  src/Favorites/Favorites.css
  src/Favorites/Favorites.tsx
  src/Form/Form.tsx
  src/QuoteCard/QuoteCard.tsx
  src/Quotes/Quotes.tsx
  src/Welcome/Welcome.tsx
  src/interfaces.tsx
Labels: documentation, enhancement

#15 Feature/cypress testing
  cypress.config.ts
  cypress/e2e/1-getting-started/todo.cy.js
  cypress/e2e/2-advanced-examples/actions.cy.js
  cypress/e2e/2-advanced-examples/aliasing.cy.js
  cypress/e2e/2-advanced-examples/assertions.cy.js
  cypress/e2e/2-advanced-examples/connectors.cy.js
  cypress/e2e/2-advanced-examples/cookies.cy.js
  cypress/e2e/2-advanced-examples/cypress_api.cy.js
  cypress/e2e/2-advanced-examples/files.cy.js
  cypress/e2e/2-advanced-examples/local_storage.cy.js
  cypress/e2e/2-advanced-examples/location.cy.js
  cypress/e2e/2-advanced-examples/misc.cy.js
  cypress/e2e/2-advanced-examples/navigation.cy.js
  cypress/e2e/2-advanced-examples/network_requests.cy.js
  cypress/e2e/2-advanced-examples/querying.cy.js
  cypress/e2e/2-advanced-examples/spies_stubs_clocks.cy.js
  cypress/e2e/2-advanced-examples/traversal.cy.js
  cypress/e2e/2-advanced-examples/utilities.cy.js
  cypress/e2e/2-advanced-examples/viewport.cy.js
  cypress/e2e/2-advanced-examples/waiting.cy.js
  cypress/e2e/2-advanced-examples/window.cy.js
  cypress/e2e/favorites_spec.cy.ts
  cypress/e2e/home_spec.cy.ts
  cypress/e2e/welcome_spec.cy.ts
  cypress/fixtures/example.json
  cypress/fixtures/fairness_quotes.json
  cypress/support/commands.ts
  cypress/support/e2e.ts
  src/App/App.tsx
  src/Form/Form.tsx
  src/Welcome/Welcome.tsx
Labels: testing

#17 add useEffect to quote card to check for favorite. Add delete functionality to delete button
  src/Favorites/Favorites.tsx
  src/QuoteCard/QuoteCard.tsx
  src/Quotes/Quotes.tsx
Labels: enhancement

#19 Feature/create favorite card
  src/FavoriteCard/FavoriteCard.css
  src/FavoriteCard/FavoriteCard.tsx
  src/Favorites/Favorites.css
  src/Favorites/Favorites.tsx
Labels: enhancement

#20 add image to cards
  src/QuoteCard/QuoteCard.css
  src/QuoteCard/QuoteCard.tsx
  src/Quotes/Quotes.tsx
  src/interfaces.ts
Labels: enhancement

#22 Feature/cypress testing
  cypress/e2e/home_spec.cy.ts
  cypress/e2e/welcome_spec.cy.ts
Labels: testing

#25 Feature/display daily quote
  src/App/App.tsx
  src/QuoteCard/QuoteCard.css
  src/dailyquote/DailyQuote.css
  src/dailyquote/DailyQuote.tsx
Labels: enhancement

#29 Testing/favorites
  cypress/e2e/favorites_spec.cy.ts
  cypress/e2e/home_spec.cy.ts
  cypress/fixtures/daily_quote.json
  cypress/fixtures/favorites.json
Labels: testing

#31 Feature/add error handling
  src/Components/App/App.tsx
  src/Components/Form/Form.tsx
  src/Components/dailyquote/DailyQuote.tsx
  src/interfaces.ts
Labels: enhancement

#36 Refactor/css footer
  src/Components/App/App.css
  src/Components/App/App.tsx
  src/Components/FavoriteCard/FavoriteCard.css
  src/Components/Favorites/Favorites.css
  src/Components/Footer/Footer.css
  src/Components/Footer/Footer.tsx
  src/Components/Form/Form.css
  src/Components/QuoteCard/QuoteCard.css
  src/Components/Quotes/Quotes.css
  src/Components/Welcome/Welcome.css
  src/Components/dailyquote/DailyQuote.css
Labels: enhancement

#37 Testing/error handling
  cypress/e2e/1-getting-started/todo.cy.js
  cypress/e2e/2-advanced-examples/actions.cy.js
  cypress/e2e/2-advanced-examples/aliasing.cy.js
  cypress/e2e/2-advanced-examples/assertions.cy.js
  cypress/e2e/2-advanced-examples/connectors.cy.js
  cypress/e2e/2-advanced-examples/cookies.cy.js
  cypress/e2e/2-advanced-examples/cypress_api.cy.js
  cypress/e2e/2-advanced-examples/files.cy.js
  cypress/e2e/2-advanced-examples/local_storage.cy.js
  cypress/e2e/2-advanced-examples/location.cy.js
  cypress/e2e/2-advanced-examples/misc.cy.js
  cypress/e2e/2-advanced-examples/navigation.cy.js
  cypress/e2e/2-advanced-examples/network_requests.cy.js
  cypress/e2e/2-advanced-examples/querying.cy.js
  cypress/e2e/2-advanced-examples/spies_stubs_clocks.cy.js
  cypress/e2e/2-advanced-examples/traversal.cy.js
  cypress/e2e/2-advanced-examples/utilities.cy.js
  cypress/e2e/2-advanced-examples/viewport.cy.js
  cypress/e2e/2-advanced-examples/waiting.cy.js
  cypress/e2e/2-advanced-examples/window.cy.js
  cypress/e2e/favorites_spec.cy.ts
  cypress/e2e/home_spec.cy.ts
  cypress/fixtures/example.json
  cypress/fixtures/favorites.json
  src/Components/App/App.tsx
  src/Components/Form/Form.tsx
  src/Components/dailyquote/DailyQuote.tsx
  src/interfaces.ts
Labels: testing
